name: cookiecutter
version: 0.0.1
description: Port of cookiecutter to dart.
author: Kasper Peulen <kasperpeulen@gmail.com>
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  which: '^0.1.3'
  path: '^1.3.6'
  logging: '^0.11.2'
  prompt: '^0.1.7'
  yaml: '^2.1.7'
  glob: '^1.0.5'
  mustache4dart: '^1.0.10'
dev_dependencies:
  test: '^0.12.4+9'
